"""Produce a compact copy of the detector for uploading to the Limelight.

WHY THIS EXISTS: the Limelight's websocket drops any message over about 16 KB.
Its web editor does not tell you -- it prints "Saving..." and silently discards
the script, so the camera keeps running whatever it had before. Our commented
source is 16.4 KB, which lands just over the line.

So the repo keeps the readable version (comments are what make it teachable) and
this generates a stripped twin to paste into the camera. Behaviour is identical:
only comments, docstrings and blank lines are removed, never code.

    ../.venv/bin/python make_deployable.py
    -> writes ../snapscript/ball_detector.deploy.py
"""

import io
import os
import sys
import tokenize

HEADER = (
    "# BIOBUZZ ball detector -- COMPACT BUILD, do not edit this file.\n"
    "# Generated by tools/make_deployable.py from snapscript/ball_detector.py,\n"
    "# which is the readable version with all the comments and the reasoning.\n"
    "# Stripped because the Limelight silently drops scripts over ~16 KB.\n"
)

LIMIT = 16384   # uWebSockets default max payload, minus room for the frame header
SAFE = LIMIT - 256


def strip(source: str) -> str:
    """Remove comments and docstrings, keep every executable token."""
    out = []
    prev_end = (1, 0)
    prev_toktype = tokenize.INDENT
    readline = io.StringIO(source).readline
    for tok in tokenize.generate_tokens(readline):
        ttype, tstr, start, end, _ = tok
        if start[0] > prev_end[0]:
            prev_end = (start[0], 0)
        if start[1] > prev_end[1]:
            out.append(" " * (start[1] - prev_end[1]))
        if ttype == tokenize.COMMENT:
            pass
        elif ttype == tokenize.STRING and prev_toktype in (
                tokenize.INDENT, tokenize.NEWLINE, tokenize.NL, tokenize.DEDENT):
            # A bare string at statement level is a docstring; drop it.
            pass
        else:
            out.append(tstr)
        prev_toktype = ttype
        prev_end = end
    text = "".join(out)
    return "\n".join(l for l in text.splitlines() if l.strip())


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src_path = os.path.join(here, "..", "snapscript", "ball_detector.py")
    out_path = os.path.join(here, "..", "snapscript", "ball_detector.deploy.py")

    source = open(src_path).read()
    compact = HEADER + strip(source) + "\n"

    # Prove it still parses and still exposes what the robot contract needs.
    compile(compact, "ball_detector.deploy.py", "exec")
    for needed in ("def runPipeline", "BALL_CLASSES", "CALIB_FOCAL_X", "MIN_SHAPE"):
        if needed not in compact:
            print("ERROR: stripping lost %r -- refusing to write" % needed)
            return 1

    open(out_path, "w").write(compact)
    before, after = len(source), len(compact)
    print("readable source : %6d bytes" % before)
    print("compact build   : %6d bytes  (%.0f%% smaller)" % (after, 100 * (1 - after / before)))
    print("limelight limit : %6d bytes" % LIMIT)
    if after > SAFE:
        print("STILL TOO BIG -- the camera will silently drop this.")
        return 1
    print("headroom        : %6d bytes -- OK" % (SAFE - after))
    print("\nwrote %s" % os.path.normpath(out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
