# BIOBUZZ ball detector -- COMPACT BUILD, do not edit this file.
# Generated by tools/make_deployable.py from snapscript/ball_detector.py,
# which is the readable version with all the comments and the reasoning.
# Stripped because the Limelight silently drops scripts over ~16 KB.
import cv2
import numpy as np
import math
POLLEN_M = 0.0725    
NECTAR_M = 0.0914    
CLASS_POLLEN      = 1
CLASS_NECTAR_RED  = 2
CLASS_NECTAR_BLUE = 3
BALL_CLASSES = [
    (CLASS_POLLEN, "POLLEN",
     [((15, 110, 80), (38, 255, 255))], POLLEN_M),
    (CLASS_NECTAR_RED, "NECTAR-RED",
     [((0, 110, 70), (9, 255, 255)), ((168, 110, 70), (179, 255, 255))], NECTAR_M),
    (CLASS_NECTAR_BLUE, "NECTAR-BLUE",
     [((100, 100, 50), (130, 255, 255))], NECTAR_M),
]
SPECK_K  = 3      
CLOSE_K  = 5      
CLOSE_IT = 1      
OPEN_K   = 5      
MIN_AREA_BY_CLASS = {
    1: 120,    
    2: 400,    
    3: 200,    
}
MIN_AREA = 120    
MIN_FILL = 0.55   
MIN_CIRC = 0.65
MIN_SHAPE = 0.62
HOUGH_BY_CLASS = {
    1: True,     
    2: False,    
    3: True,     
}
HOUGH_FALLBACK   = True    
HOUGH_MIN_BLOB   = 4000    
HOUGH_MIN_FILL   = 0.55    
CALIB_RES_X   = 1280.0
CALIB_FOCAL_X = 1221.445
CALIB_FOCAL_Y = 1223.398
CALIB_CX      = 637.226
CALIB_CY      = 502.549
HFOV_OVERRIDE_DEG = None
_intrinsics_cache = {}
def _intrinsics(width, height):
    key = (width, height, HFOV_OVERRIDE_DEG)
    if key not in _intrinsics_cache:
        if HFOV_OVERRIDE_DEG is not None:
            f = (width / 2.0) / math.tan(math.radians(HFOV_OVERRIDE_DEG) / 2.0)
            _intrinsics_cache[key] = (f, f, width / 2.0, height / 2.0)
        else:
            scale = width / CALIB_RES_X
            _intrinsics_cache[key] = (CALIB_FOCAL_X * scale, CALIB_FOCAL_Y * scale,
                                      CALIB_CX * scale, CALIB_CY * scale)
    return _intrinsics_cache[key]
def _build_mask(hsv, ranges):
    mask = None
    for lo, hi in ranges:
        part = cv2.inRange(hsv, np.array(lo, dtype=np.uint8), np.array(hi, dtype=np.uint8))
        mask = part if mask is None else cv2.bitwise_or(mask, part)
    if SPECK_K > 1:
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE, (SPECK_K, SPECK_K)))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE, (CLOSE_K, CLOSE_K)), iterations=CLOSE_IT)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE, (OPEN_K, OPEN_K)))
    return mask
def _hough_recover(mask, image):
    blur = cv2.GaussianBlur(mask, (9, 9), 2)
    circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, dp=1.5, minDist=60,
                               param1=100, param2=40, minRadius=12, maxRadius=200)
    if circles is None:
        return None
    cx, cy, r = circles[0][0]          
    if r <= 1:
        return None
    probe = np.zeros(mask.shape, dtype=np.uint8)
    cv2.circle(probe, (int(cx), int(cy)), int(r), 255, -1)
    disk = float(np.count_nonzero(probe))
    if disk <= 0:
        return None
    fill = float(np.count_nonzero(cv2.bitwise_and(probe, mask))) / disk
    if fill < HOUGH_MIN_FILL:
        return None
    return float(cx), float(cy), float(r), fill
def _best_in_mask(mask, image, min_area, allow_hough):
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    best = None
    largest_rejected = 0.0
    for c in contours:
        area = cv2.contourArea(c)
        if area < min_area:
            continue
        hull = cv2.convexHull(c)
        hull_area = cv2.contourArea(hull)
        if hull_area <= 0:
            continue
        (cx, cy), r = cv2.minEnclosingCircle(hull)
        if r <= 1:
            continue
        fill = area / hull_area                 
        circ = hull_area / (math.pi * r * r)     
        if fill < MIN_FILL or circ < MIN_CIRC or fill * circ < MIN_SHAPE:
            largest_rejected = max(largest_rejected, hull_area)
            cv2.drawContours(image, [hull], -1, (0, 0, 255), 1)   
            continue
        if best is None or r > best[2]:
            best = (cx, cy, r, fill * circ, c, 1)
    if best is not None:
        return best
    if not (HOUGH_FALLBACK and allow_hough and largest_rejected >= HOUGH_MIN_BLOB):
        return None
    rec = _hough_recover(mask, image)
    if rec is None:
        return None
    cx, cy, r, fillfrac = rec
    poly = cv2.ellipse2Poly((int(cx), int(cy)), (int(r), int(r)), 0, 0, 360, 10)
    return (cx, cy, r, fillfrac, poly.reshape(-1, 1, 2), 2)
def runPipeline(image, llrobot):
    llpython = [0, 0, 0, 0, 0, 0, 0, 0]
    h, w = image.shape[:2]
    focal_x, focal_y, centre_x, centre_y = _intrinsics(w, h)
    focal_mean = 0.5 * (focal_x + focal_y)
    wanted = 0
    try:
        if llrobot is not None and len(llrobot) > 0:
            wanted = int(llrobot[0])
    except (TypeError, ValueError):
        wanted = 0
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    winner = None
    for class_id, class_name, ranges, diameter_m in BALL_CLASSES:
        if wanted and class_id != wanted:
            continue
        mask = _build_mask(hsv, ranges)
        cand = _best_in_mask(mask, image,
                             MIN_AREA_BY_CLASS.get(class_id, MIN_AREA),
                             HOUGH_BY_CLASS.get(class_id, False))
        if cand is None:
            continue
        cx, cy, r, score, contour, source = cand
        dist = (diameter_m * focal_mean) / (2.0 * r)
        if winner is None or dist < winner[0]:
            winner = (dist, class_id, class_name, cx, cy, r, score, contour, source)
    if winner is None:
        return np.array([[]]), image, llpython
    dist, class_id, class_name, cx, cy, r, score, contour, source = winner
    tx = math.degrees(math.atan2(cx - centre_x, focal_x))
    ty = math.degrees(math.atan2(centre_y - cy, focal_y))
    colour = (0, 255, 0) if source == 1 else (0, 200, 255)
    cv2.circle(image, (int(cx), int(cy)), int(r), colour, 2)
    cv2.circle(image, (int(cx), int(cy)), 3, (255, 0, 255), -1)
    cv2.putText(image, "%s  %.2fm  tx %.1f%s" % (
                class_name, dist, tx, "" if source == 1 else "  [hough]"),
                (int(cx - r), int(cy - r) - 8),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, colour, 1)
    llpython = [class_id * 10 + source, tx, ty, dist, cx, cy, r, score]
    return contour, image, llpython
